#!/bin/bash

# EDIT these paths to your directories, respectively:

# MaskRCNN folder (delete the word "#" from the beginning of the line and set the path if you already have
# a MaskRCNN folder - in this case, move the word "rem" from between the beginning of the last 2 lines):
# PATHTOINSERT="/home/biomag/path/Mask_RCNN-2.1"

# working directory where you downloaded the code and will have the output under ~\kaggle_workflow\outputs\postprocessing:
ROOT_DIR="."

# directory of your masks for style transfer learning input. Provide ONLY if you have custom masks for your input
# images, otherwise the default folder will be the presegmented masks generated by our pipeline.
#IMAGES_DIR="maskFolder"
# -----------------------------------------------------------------------------


# --- DO NOT EDIT from here ---
# run_workflow_prepareStyle4singleExperiment.sh $ROOT_DIR $IMAGES_DIR
source run_workflow_prepareStyle4singleExperiment.sh $ROOT_DIR